### ISSUE TITLE
Unable to run Scaffold with HAM-1000 dataset

### ISSUE THREAD

**Issue by ybouilla** [owkin/FLamby#251]
Hi all, 

I am trying to run a model with scaffold using HAM-1000 dataset (ie Isic2019)

Here the error i got:
```Traceback (most recent call last):
  File "flamby_test_ham.py", line 90, in <module>
    s.run()
  File "/my/computer/flamby/FLamby/flamby/strategies/fed_avg.py", line 199, in run
    self.perform_round()
  File "/my/computerflamby/FLamby/flamby/strategies/scaffold.py", line 199, in perform_round
    self._local_optimization(
  File "/my/computerflamby/FLamby/flamby/strategies/scaffold.py", line 154, in _local_optimization
    _model._local_train_with_correction(
  File "/my/computerflamby/FLamby/flamby/strategies/utils.py", line 348, in _local_train_with_correction
    _corrected_loss = self._loss(_pred, y)
  File "/my/computer/home/.conda/envs/flamby/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1190, in _call_impl
    return forward_call(*input, **kwargs)
  File "/my/computer/home/.conda/envs/flamby/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 619, in forward
    return F.binary_cross_entropy(input, target, weight=self.weight, reduction=self.reduction)
  File "/my/computer/home/.conda/envs/flamby/lib/python3.8/site-packages/torch/nn/functional.py", line 3086, in binary_cross_entropy
    raise ValueError(
ValueError: Using a target size (torch.Size([10, 1])) that is different to the input size (torch.Size([10, 8])) is deprecated. Please ensure they have the same size.
```

Issue is mainly due to newer version of pytorch

Thanks for your time

**Comment by jeandut** [comment]
Hi @ybouilla ! Your error is very hard to debug without any companion code. Can you please provide an Minium Working Example to reproduce your bug ? Thanks again !

**Comment by jeandut** [comment]
@ybouilla in the absence of answers from you I will close this issue. Do not hesitate to reopen it.
