### ISSUE TITLE
CI issue: numba does not support Python3.11

### ISSUE THREAD

**Issue by jeandut** [owkin/FLamby#255]
Recently the CI has stopped working at the install dependencies step it might be due (or not) to the CI pulling the latest Python version (3.11) and [numba not being yet supported for this version](https://github.com/numba/llvmlite/issues/885).
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-4i7g54c_/numba_7c1e3072e1914838993f4ec1d7ecca04/setup.py", line 51, in <module>
          _guard_py_ver()
        File "/tmp/pip-install-4i7g54c_/numba_7c1e3072e1914838993f4ec1d7ecca04/setup.py", line 48, in _guard_py_ver
          raise RuntimeError(msg.format(cur_py, min_py, max_py))
      RuntimeError: Cannot install on Python version 3.11.0; only versions >=3.7,<3.11 are supported.
      [end of output]

**Comment by jeandut** [comment]
If it indeed stems from there fixing the Python version used in the docker image to be <3.11 should solve the problem, what do you think @maikia ?

**Comment by jeandut** [comment]
I guess the syntax
```
with:
    python-version: '3.10' 
```
Should suffice with a doc update to say we do not support 3.11 yet ?
Do you want to take care of this PR ?

**Comment by jeandut** [comment]
Closed by #258
